# Generated by Django 2.1 on 2019-07-21 09:44

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/%Y/%m/%d', verbose_name='轮播图')),
                ('index', models.IntegerField(default=1, verbose_name='轮播顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播商品',
                'verbose_name_plural': '轮播商品',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_sn', models.CharField(max_length=50, verbose_name='商品编号')),
                ('name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('cover', models.ImageField(upload_to='covers/%Y/%m/%d', verbose_name='商品封面')),
                ('good_num', models.IntegerField(verbose_name='商品数量')),
                ('sold_num', models.IntegerField(verbose_name='销售数量')),
                ('click_num', models.IntegerField(verbose_name='点击数量')),
                ('fav_num', models.IntegerField(verbose_name='收藏数量')),
                ('desc', models.TextField(verbose_name='商品简介')),
                ('market_price', models.FloatField(verbose_name='市场价格')),
                ('sold_price', models.FloatField(verbose_name='销售价格')),
                ('detail', ckeditor.fields.RichTextField(verbose_name='商品详情')),
                ('is_fare', models.BooleanField(verbose_name='是否包邮')),
                ('is_hot', models.BooleanField(verbose_name='是否热卖')),
                ('is_new', models.BooleanField(verbose_name='是否新品')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
            },
        ),
        migrations.CreateModel(
            name='GoodCarouselImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='goods/%Y/%m/%d', verbose_name='商品封面')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Good', verbose_name='所属商品')),
            ],
            options={
                'verbose_name': '轮播图片',
                'verbose_name_plural': '轮播图片',
            },
        ),
        migrations.CreateModel(
            name='GoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='商品名称', max_length=20, verbose_name='商品名称')),
                ('code', models.CharField(max_length=10, verbose_name='类别code')),
                ('desc', models.TextField(verbose_name='商品描述')),
                ('category_type', models.IntegerField(choices=[(1, '一级分类'), (2, '二级分类'), (3, '三级分类')], verbose_name='分类类型')),
                ('is_banner', models.BooleanField(default=False, verbose_name='是否横幅')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='goods.GoodCategory', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
            },
        ),
        migrations.CreateModel(
            name='GoodCategoryBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='品牌名称')),
                ('desc', models.TextField(verbose_name='品牌描述')),
                ('image', models.ImageField(upload_to='brands/%Y/%m/%d', verbose_name='品牌logo')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '品牌名',
                'verbose_name_plural': '品牌名',
            },
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodCategory', verbose_name='商品分类'),
        ),
        migrations.AddField(
            model_name='carouselgood',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Good', verbose_name='所属商品'),
        ),
    ]
