# Generated by Django 2.1 on 2019-07-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190721_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='good_num',
            field=models.IntegerField(default=0, verbose_name='商品数量'),
        ),
    ]
