# Generated by Django 2.1 on 2019-07-21 13:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20190721_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='点击数量'),
        ),
        migrations.AlterField(
            model_name='good',
            name='detail',
            field=ckeditor.fields.RichTextField(default='', verbose_name='商品详情'),
        ),
        migrations.AlterField(
            model_name='good',
            name='fav_num',
            field=models.IntegerField(default=0, verbose_name='收藏数量'),
        ),
        migrations.AlterField(
            model_name='good',
            name='is_fare',
            field=models.BooleanField(default=False, verbose_name='是否包邮'),
        ),
        migrations.AlterField(
            model_name='good',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='是否热卖'),
        ),
        migrations.AlterField(
            model_name='good',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='是否新品'),
        ),
        migrations.AlterField(
            model_name='good',
            name='market_price',
            field=models.FloatField(default=0, verbose_name='市场价格'),
        ),
        migrations.AlterField(
            model_name='good',
            name='sold_num',
            field=models.IntegerField(default=0, verbose_name='销售数量'),
        ),
        migrations.AlterField(
            model_name='good',
            name='sold_price',
            field=models.FloatField(default=0, verbose_name='销售价格'),
        ),
    ]
