# Generated by Django 2.1 on 2019-07-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20190721_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='desc',
            new_name='good_desc',
        ),
        migrations.RenameField(
            model_name='good',
            old_name='detail',
            new_name='good_detail',
        ),
    ]
