# Generated by Django 2.1 on 2019-07-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20190721_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselgood',
            name='image',
            field=models.ImageField(upload_to='banner/%Y/%m/%d', verbose_name='轮播图'),
        ),
        migrations.AlterField(
            model_name='good',
            name='cover',
            field=models.ImageField(upload_to='cover/%Y/%m/%d', verbose_name='商品封面'),
        ),
        migrations.AlterField(
            model_name='goodcarouselimage',
            name='image',
            field=models.ImageField(upload_to='banner/%Y/%m/%d', verbose_name='商品封面'),
        ),
        migrations.AlterField(
            model_name='goodcategorybrand',
            name='image',
            field=models.ImageField(upload_to='brands/%Y/%m/%d', verbose_name='品牌logo'),
        ),
    ]
