# Generated by Django 2.1 on 2019-07-24 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_auto_20190724_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good', to='trades.PayInfo', verbose_name='支付信息'),
        ),
    ]
