# Generated by Django 2.1 on 2019-07-21 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': '收货地址', 'verbose_name_plural': '收货地址'},
        ),
    ]
