# Generated by Django 2.1 on 2019-07-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190721_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='手机号'),
        ),
    ]
