# Generated by Django 2.1 on 2019-07-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190723_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='stamp',
            field=models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='邮编'),
        ),
    ]
